concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-runner"
  url = "http://gitlab/"
  id = 1
  token = "token"
  token_obtained_at = 2022-12-01T01:43:34Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  environment = ["DOCKER_AUTH_CONFIG={\"auths\":{\"registry.nexus.domain.com\":{\"auth\":\"base64_encoded_id_pw\"}}}"]
  [runners.custom_build_dir]
  [runners.cache]
    Type = "s3"
    Shared = true
    [runners.cache.s3]
      ServerAddress = "minio.domain.com"
      AccessKey = "access_key"
      SecretKey = "secret_key"
      BucketName = "private-gitlab-ci"
      Insecure = true
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:20.10.18"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = true
    # volumes = ["/cache"]
    shm_size = 0