version: "3.9"

networks: 
  docker-host:
    name: docker-host
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 
          gateway: 172.20.0.1

volumes:
  gitlab-config:
    name: gitlab-config
  gitlab-data:
    name: gitlab-data
  gitlab-logs:
    name: gitlab-logs
  nexus-data:
    name: nexus-data
  minio-data:
    name: minio-data

services:
  nginx-proxy:
    image: nginx:1.23.2
    container_name: nginx-proxy
    hostname: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/nginx/conf.d
    networks: 
      docker-host:
        ipv4_address: 172.20.0.2

  gitlab:
    image: gitlab/gitlab-ee:15.5.3-ee.0
    container_name: gitlab
    hostname: gitlab
    restart: always
    volumes: 
      - type: volume
        source: gitlab-config
        target: /etc/gitlab
      - type: volume
        source: gitlab-data
        target: /var/opt/gitlab
      - type: volume
        source: gitlab-logs
        target: /var/log/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://gitlab.domain.com"
        registry_external_url "http://registry.gitlab.domain.com"
    networks: 
      docker-host:
        ipv4_address: 172.20.0.10

  gitlab-runner:
    image: gitlab/gitlab-runner:v15.5.0
    container_name: gitlab-runner
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./gitlab-runner
        target: /etc/gitlab-runner
    networks: 
      docker-host:
        ipv4_address: 172.20.0.11

  nexus:
    image: sonatype/nexus3:3.42.0
    container_name: nexus
    hostname: nexus
    restart: always
    volumes:
      - type: volume
        source: nexus-data
        target: /nexus-data
    networks: 
      docker-host:
        ipv4_address: 172.20.0.20

  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    restart: always
    volumes:
      - type: volume
        source: minio-data
        target: /data
    environment:
      MINIO_ROOT_USER: change_me
      MINIO_ROOT_PASSWORD: change_me
    command: server /data --console-address ":9001"
    shm_size: '1gb'
    networks: 
      docker-host:
        ipv4_address: 172.20.0.30